version: '2.1'
services:
  prism-mongo:
    container_name: prism-mongo
    image: mongo
    restart: always
    healthcheck:
      test: mongo --eval 'db.getCollectionNames()'
      interval: 10s
      timeout: 2s
      retries: 10
    volumes:
      - prism-mongodb-vol:/data/db
    ports:
      - 127.0.0.1:27017:27017
    networks:
      - services-tier

  prism-node:
    container_name: prism-node
    restart: always
    depends_on:
      prism-mongo:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - services-tier
    ports:
      - $GLS_CONNECTOR_HOST:$GLS_CONNECTOR_PORT:$GLS_CONNECTOR_PORT
      - $GLS_METRICS_HOST:$GLS_METRICS_PORT:$GLS_METRICS_PORT
    env_file:
      - .env

volumes:
  prism-mongodb-vol:
  prism-elastic-vol:

networks:
  services-tier:
