version: '2.1'
services:
  prism-mongo:
    container_name: prism-mongo
    image: mongo
    restart: always
    healthcheck:
      test: mongo --eval 'db.getCollectionNames()'
      interval: 10s
      timeout: 2s
      retries: 10
    volumes:
      - prism-mongodb-vol:/data/db
    ports:
      - 127.0.0.1:27017:27017
    networks:
      - services-tier
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  slave-mongo:
    container_name: slave-mongo
    image: mongo
    ports:
      - 27018:27017
    restart: always
    networks:
      - services-tier
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  prism-node:
    container_name: prism-node
    restart: always
    depends_on:
      prism-mongo:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - services-tier
    ports:
      - $GLS_CONNECTOR_HOST:$GLS_CONNECTOR_PORT:$GLS_CONNECTOR_PORT
      - $GLS_METRICS_HOST:$GLS_METRICS_PORT:$GLS_METRICS_PORT
    env_file:
      - .env

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.5.0
    networks:
      - services-tier
    ports:
      - 127.0.0.1:9200:9200
    healthcheck:
      test: curl http://127.0.0.1:9200/_cat/health
    environment:
      'discovery.type': 'single-node'
      'bootstrap.memory_lock': 'true'
      'ES_JAVA_OPTS': '-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - prism-elastic-vol:/usr/share/elasticsearch/data

  monstache:
    image: rwynn/monstache
    container_name: monstache
    working_dir: /app
    command: -f ./monstache.example.config.toml
    volumes:
      - $PWD/search-configs/monstache.example.config.toml:/app/monstache.example.config.toml
      - $PWD/search-configs/parsePost.js:/app/parsePost.js
      - $PWD/search-configs/parseProfile.js:/app/parseProfile.js
      - $PWD/search-configs/parseCommunity.js:/app/parseCommunity.js
    depends_on:
      prism-mongo:
        condition: service_started
      elasticsearch:
        condition: service_healthy
    networks:
      - services-tier


volumes:
  prism-mongodb-vol:
  prism-elastic-vol:

networks:
  services-tier:
